# Generated by Django 5.0.4 on 2024-04-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rick',
            name='is_morty_alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rick',
            name='universe',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
