# Generated by Django 5.0.4 on 2024-04-29 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ricks', '0002_alter_rick_is_morty_alive_alter_rick_universe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rick',
            name='is_morty_alive',
        ),
    ]
