# Generated by Django 5.0.4 on 2024-04-30 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morties', '0001_initial'),
        ('ricks', '0003_remove_rick_is_morty_alive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morty',
            name='paired_rick',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='paired_morty', to='ricks.rick'),
        ),
    ]
