# Generated by Django 5.0.4 on 2024-05-04 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morties', '0001_initial'),
        ('ricks', '0003_remove_rick_is_morty_alive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morty',
            name='is_alive',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='morty',
            name='paired_rick',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paired_morty', to='ricks.rick'),
        ),
    ]
