# Generated by Django 5.0.4 on 2024-05-06 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morties', '0002_alter_morty_is_alive_alter_morty_paired_rick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morty',
            name='paired_rick',
        ),
    ]
