# Generated by Django 5.0.4 on 2024-05-10 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morties', '0003_remove_morty_paired_rick'),
        ('ricks', '0005_remove_rick_paired_morty'),
    ]

    operations = [
        migrations.AddField(
            model_name='morty',
            name='paired_rick',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paired_morties', to='ricks.rick'),
        ),
    ]
