# Generated by Django 5.0.4 on 2024-04-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morties', '0004_alter_morty_paired_rick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morty',
            name='is_alive',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
